name: deeplearnjs_facade
description: A light dart wrapper around deelearnjs
version: 0.0.1
homepage: https://github.com/jackd/deeplearnjs-dart-facade
author: Dominic Jack <thedomjack@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  js: ^0.6.0
  func: ^1.0.0

dev_dependencies:
  test: ^0.12.0
  browser: '>=0.10.0 <0.11.0'
  dart_to_js_script_rewriter: '^1.0.1'

transformers:
- dart_to_js_script_rewriter
